# Generated by Django 4.0.3 on 2024-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='color',
            field=models.CharField(default='silk', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='fabric',
            field=models.CharField(default='silk', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hat',
            name='pic_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hat',
            name='style_name',
            field=models.CharField(default='cool', max_length=200),
            preserve_default=False,
        ),
    ]
